### ISSUE TITLE
reftree v1.2.0 Not published for Scala 2.12?

### ISSUE THREAD

**Issue by KyleU** [stanch/reftree#16]
I don't see the 2.12 artifacts on Jcenter, and depending on `"org.stanch" %% "reftree" % "1.1.3"` fails as well. Is there a different repo I should be using?

https://jcenter.bintray.com/org/stanch/

**Comment by KyleU** [comment]
Whoops, forgot to add `resolvers += Resolver.bintrayRepo("stanch", "maven")`

**Comment by KyleU** [comment]
1.2.0 still isn't published for 2.12, but runs file with 1.1.3

**Comment by stanch** [comment]
Sorry for the late reply, missed this! 1.2.0 is now published for 2.12.
