### ISSUE TITLE
Installation instructions incomplete, no cross-publishing for 1.2.0

### ISSUE THREAD

**Issue by wsargent** [stanch/reftree#17]
When I look at the https://stanch.github.io/reftree/#including-in-your-project it says 1.2.0 is the latest.  
In addition, the documentation does not specify that you are using bintray and so need to add a bintray resolver:

```
resolvers += Resolver.bintrayRepo("stanch", "reftree"),
```

The latest version on mvnrepository is 1.1.3:

https://mvnrepository.com/artifact/org.stanch/reftree

If I go to bintray directly then it does tell me it's 1.2.0:

https://bintray.com/stanch/maven/reftree/1.2.0

But it appears that 1.2.0 was only published for Scala 2.11, not 2.12 (it was not cross-published):

* https://dl.bintray.com/stanch/maven/org/stanch/reftree_2.11/1.2.0/ works
* https://dl.bintray.com/stanch/maven/org/stanch/reftree_2.12/1.2.0/ is 404

Finally, the gitbook demo is flaky -- if I type "makeSite" twice in a row then it fails with some npm exception.  Not sure what's up with that.

**Comment by wsargent** [comment]
Doing an `sbt +publishLocal` worked to some extent, but I am still missing some things:

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.stanch#zipper_2.12;0.5.1: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
```

**Comment by stanch** [comment]
Thanks for reporting this!

> In addition, the documentation does not specify that you are using bintray and so need to add a bintray resolver.

My understanding was that sbt includes `Resolver.jcenterRepo` by default. I just checked that on clean project, and it seems to be the case. The problem appears to be that 1.2.0 for Scala 2.12 was not published to Bintray (see below).

> The latest version on mvnrepository is 1.1.3

Not sure how it made it to mvnrepository. I only published it to Bintray.

> But it appears that 1.2.0 was only published for Scala 2.11, not 2.12 (it was not cross-published)

Fixed, not sure what went wrong there. Might take some time to sync to jCenter, but you can use the resolver you mentioned in the meantime.

> Finally, the gitbook demo is flaky -- if I type "makeSite" twice in a row then it fails with some npm exception. Not sure what's up with that.

May I ask what a “gitbook demo” is? Also, can you be more specific about the npm exception?

> `sbt.librarymanagement.ResolveException: unresolved dependency: org.stanch#zipper_2.12;0.5.1: not found`

You still need the resolver for this. Again, `Resolver.jcenterRepo` should work and should be included by default. If that’s not the case, I can amend the instructions.

**Comment by stanch** [comment]
Actually, I think jCenter might not be doing a good job... It seems to only contain one Scala version flavor of everything: https://jcenter.bintray.com/org/stanch/

**Comment by wsargent** [comment]
Did you run  sbt "+publish"?  The plus sign really messes things up.

Seems to work now! https://dl.bintray.com/stanch/maven/org/stanch/reftree_2.12/1.2.0/
