### ISSUE TITLE
Add support for Scala 2.13

### ISSUE THREAD

**Issue by danicheg** [stanch/reftree#35]
Hey there! Is there any chance to publish this library for Scala 2.13? Or maybe if there is a PR from the community, would it be possible to merge it (asking for a friend :smile:)?

**Comment by stanch** [comment]
Hey @danicheg, see this comment: https://github.com/stanch/reftree/issues/22#issuecomment-754659656. In short, happy to accept a PR, but it would need to involve updating the zipper library as well, and also updating the `RefTree` instances for 2.13 collections.

**Comment by danicheg** [comment]
Thanks for the quick answer! Hopefully, I will have time to delve into this in the upcoming weeks.
