### ISSUE TITLE
Unescaped special characters

### ISSUE THREAD

**Issue by sakshamsharma** [stanch/reftree#7]
While trying to print an AST of a program, I tried renaming a node to `<` for instance.

Reftree does not fail on that, but when it tries to render the resulting dotfile using dot, the error is thrown by dot. Oh, and no, it isn't a clear error.

Perhaps special characters needed by dot should be escaped somehow?

**Comment by stanch** [comment]
Thanks! This reminded me that I fixed it in a local branch :)

**Comment by stanch** [comment]
By the way, 0.8.2 is already released with this fix.

**Comment by sakshamsharma** [comment]
Sounds great! Thanks!
