### ISSUE TITLE
Vertical sequential list

### ISSUE THREAD

**Issue by sakshamsharma** [stanch/reftree#8]
Can we have an implicit for drawing a vertical sequential list?
Something like:
```
abcd
    |
efgh
    |
ijkl
    |
end
```

I was using something like this, but it crashes on some very simple inputs (flowName is a string)
```
  implicit def cfListDrawer: ToRefTree[List[CFEnum]] = ToRefTree[List[CFEnum]] {
    case x::xs => RefTree.Ref(x, Seq(xs.refTree)).rename(x.flowName)
    case Nil => RefTree.Ref("", Seq()).rename("End")
  }
```

Would be useful for vertical flow diagrams.

**Comment by stanch** [comment]
Could you elaborate what is the difference between this and a normal `List` diagram? Also how does it crash?
