### ISSUE TITLE
No 2.12 support

### ISSUE THREAD

**Issue by hejfelix** [stanch/reftree#9]
I was going to give it a spin, but no 2.12 support stopped me. 2.12 has been our for a long time, how come it's only released as 2.11?

**Comment by hejfelix** [comment]
As I'm looking at your repo, it does state that there's 2.12. Maybe I'm not adding the repository correctly.

**Comment by stanch** [comment]
@hejfelix Which version are you using? Could you show how you are adding the dependency? `1.0.0` is published for `2.12`: https://bintray.com/stanch/maven/reftree/1.0.0#files/org/stanch/reftree_2.12

**Comment by hejfelix** [comment]
Don't worry, it was a local mistake. I'm on 1.1.0-20170426 now :)

**Comment by stanch** [comment]
Soon there will be a `1.1.0` even with *Scala.js* support ;)
